# URL where Go versions are looked
all_releases_url = "https://go.dev/dl/"

# Directory where SDKs will be downloaded (absolute or relative path).
download_dir = "./downloads"

# Directory where SDKs will be installed.
# Typically, it is GOROOT env.
# Can be absolute or relative path.
install_dir = "./sdk"

# Directory where local binaries and cache located.
# Typically, it is GOPATH env.
# Can be absolute or relative path.
local_dir = "./local"

# Max versions number to show in list
limit = 10

# Show versions having same OS with current environment
filter_os = true

# Show versions having same architecture with current environment
filter_arch = true
